### PR TITLE
Add disclaimer wrt not-for-production

### PR DESCRIPTION
**Pull request by ignasi35**
@jroper @seglo is it correct to install 3 replicas of kafka but only one of ZK?

### CODE REVIEW

**Comment by seglo** [comment]
Three replicas would be ideal so that the cluster can survive a single node failure.  ZooKeeper requires a quorum of `ceil(2/N)` where N is the number of nodes.  In a 3 node cluster that means that it can tolerate 1 node failure and still operate.

In practice, Kafka's reliance on ZK has decreased significantly.  It's still critical for broker & leader partition elections, but these don't incur a significant amount of traffic in a healthy cluster.  You should be able to easily scale to 3 ZK nodes and give them a small resource allocation of CPU (1), Memory (non-busy cluster?  256MB would probably work), and Disk (really just topic metadata, 10GB is more than enough).

**Comment by ignasi35** [comment]
Thanks @seglo. I want to make sure we use some sensible defaults (or production-friendly examples), especially if using this code as snippets for docs.

**Comment by seglo** [comment]
OTOH If this is just a throwaway example then 1 broker and 1 zk node is fine too.  I noticed you specify the `ephemeral` storage type which is meant for dev and testing and not a cluster that will be live for any significant length of time.

To get an idea of more production-like examples of Strimzi Kafka resources you can check out the FDP docs here: https://developer.lightbend.com/docs/fast-data-platform/current-OpenShift/#kafka-resource-templates

**Comment by ignasi35** [comment]
Then I think a disclaimer on the YML file with a link to those docs is the best solution forward. It'll make it clear this is not-for-production and we won't need to maintain as we make improvements on the guide you linked. 👍🏼

**Comment by TimMoore** [comment]
Looks good, but the non-production-worthiness is not limited to only the ZooKeeper part, so perhaps it would be better to put the warning up top, on both versions of the file (here and also https://github.com/lagom/lagom-samples/blob/mastershopping-cart/deploy/specs/common/kafka-single.yaml)

**Comment by ignasi35** [comment]
> put the warning up top, on both versions of the file

done

**Pull request merged**
