### PR TITLE
Replace 'recipes' by 'samples' in package and artefacts

### LINKED ISSUE #3: Change package and artifact to samples
Projects are using `recipes` in artefact and packages. We should change to samples.

### PR DESCRIPTION
**Pull request by octonato**
Fixes #3

### CODE REVIEW

**Comment by octonato** [comment]
@ignasi35, I didn't replace the package name to `com.example` as you asked in #3. Although I agree with the suggestion, I wanted to keep it minimal. Package `com.lightbend.lagom` is also fine.

We can try to use `com.example` for new samples and we can refactor `com.lightbend.lagom` on another PR.

**Review by dwijnand — APPROVED** [review]

**Comment by ignasi35** [comment]
> Although I agree with the suggestion, I wanted to keep it minimal.

I don't understand. You wanted to keep _what_ minimal? The PR? Isn't renaming to `com.example` as minimal?

**Comment by ignasi35** [comment]
I think we could converge the couchbase samples from `org.example` to `com.lightbend.lagom.samples` too.

**Comment by ignasi35** [comment]
We should rename the directories to try to stick to `dirName === packageName` convention.

**Review by ignasi35 — CHANGES_REQUESTED** [review]
See my comment above.

**Comment by ignasi35** [comment]
🤷🏼‍♂️the build failed on the java version of couchbase persistence 🤷🏼‍♂️

**Comment by ignasi35** [comment]
I think we can postpone this massive rename until we've moved everything into this repo.

**Comment by octonato** [comment]
@ignasi35, I fixed the dir names. Changing to `com.example` requires more work because it changes the structure. It's not as simple as rename one single dir.

The couchbase is probably failling becuase of flakiness. The process in the container needs so time to setup the DB and it may happen that the tests start before the indices are ready.

**Comment by octonato** [comment]
@ignasi35, I did the change on the couchbase samples. All moved to `com.lightbend.lagom.samples`

**Comment by octonato** [comment]
@ignasi35, on your side now. Final review?

**Review by ignasi35 — APPROVED** [review]

**Pull request merged**
