### PR TITLE
[1.5.x] Use latest JDKs

### PR DESCRIPTION
**Pull request by TimMoore**
Backport of #107

### CODE REVIEW

**Comment by TimMoore** [comment]
Should 1.5.x actually be running with Java 11? It already was, before this pull request, but Cassandra seems flaky in CI. We don't certify Lagom 1.5 with Java 11. Should I remove it from this branch?

**Comment by ignasi35** [comment]
> Should 1.5.x actually be running with Java 11? It already was, before this pull request, but Cassandra seems flaky in CI. We don't certify Lagom 1.5 with Java 11. Should I remove it from this branch?

We already run the [`lagom/lagom` build jobs in JDK11](https://github.com/lagom/lagom/blob/1.5.x/.travis.yml#L52-L58). We could mark the JDK11 jobs for `lagom-samples` as `may fail` but I think we must keep them around.

**Comment by TimMoore** [comment]
The build passed after re-running, so the only thing blocking this now is an erroneously required "Travis CI - Branch" check (see https://github.com/lagom/lagom-samples/pull/114#discussion_r335839087).

**Comment by TimMoore** [comment]
I manually removed that required check (since the settings bot seems to be broken) so this just needs an approval from someone.

**Review by ignasi35 — APPROVED** [review]

**Pull request merged**
