### PR TITLE
Use latest JDKs

### PR DESCRIPTION
**Pull request by ignasi35**

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]

**Comment by TimMoore** [comment]
Travis CI didn't run on this change. Any ideas why?

**Comment by TimMoore** [comment]
Looking at https://travis-ci.com/lagom/lagom-samples/requests, my guess is that this pull request initially targeted the wrong branch, and Travis CI doesn't see an event when the branch target is updated. I'll close and reopen to trigger it.

We should probably also set it up as a required check for the 1.5.x and 1.6.x branches, so that things aren't merged by mistake without the build running. **Update:** raised as #108.

**Review by TimMoore — APPROVED** [review]
Thanks!

Is there any easier way to specify the latest patch build of each release? Otherwise this will be a constant chore. For example, OpenJDK 8u232 and 11.0.5 were both just tagged today, and I would expect AdoptOpenJDK releases to follow soon.

- https://wiki.openjdk.java.net/display/jdk8u
- https://wiki.openjdk.java.net/display/JDKUpdates/JDK11u

**Comment by TimMoore** [comment]
Had to update the Java 8 version string: 37c2f75

**Comment by TimMoore** [comment]
Backport: #110

**Comment by ignasi35** [comment]
> Had to update the Java 8 version string: [37c2f75](https://github.com/lagom/lagom-samples/commit/37c2f759f8abcd0a37c1d3205c09fb6003641fd9)

thanks @TimMoore

**Comment by ignasi35** [comment]
> Is there any easier way to specify the latest patch build of each release? Otherwise this will be a constant chore.

There certainly is. We should use the same _spell_ we use on [other repos](https://github.com/lagom/lagom/blob/master/.travis.yml#L27).

**Comment by ignasi35** [comment]
raised #111

**Pull request merged**
