### PR TITLE
Update sbt to 1.3.2

### PR DESCRIPTION
**Pull request by TimMoore**
Supersedes #82

### CODE REVIEW

**Comment by dwijnand** [comment]
```
[error] Test com.example.hello.impl.HelloServiceTest.shouldSayHelloUsingGrpc failed: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNKNOWN, took 4.159 sec
[error]     at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
[error]     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[error]     at scala.concurrent.package$.blocking(package.scala:146)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:84)
[error]     at com.example.hello.impl.HelloServiceTest.lambda$null$e30f1d53$1(HelloServiceTest.java:41)
[error]     at com.lightbend.lagom.javadsl.testkit.grpc.AkkaGrpcClientHelpers.lambda$withGrpcClient$b957ea7e$1(AkkaGrpcClientHelpers.java:38)
[error]     at com.lightbend.lagom.javadsl.testkit.grpc.AkkaGrpcClientHelpers.withGrpcClient(AkkaGrpcClientHelpers.java:65)
[error]     at com.lightbend.lagom.javadsl.testkit.grpc.AkkaGrpcClientHelpers.withGrpcClient(AkkaGrpcClientHelpers.java:41)
[error]     at com.example.hello.impl.HelloServiceTest.lambda$shouldSayHelloUsingGrpc$89d0e00e$1(HelloServiceTest.java:32)
[error]     at com.lightbend.lagom.javadsl.testkit.ServiceTest$.withServer(ServiceTest.scala:323)
[error]     at com.lightbend.lagom.javadsl.testkit.ServiceTest.withServer(ServiceTest.scala)
[error]     at com.example.hello.impl.HelloServiceTest.shouldSayHelloUsingGrpc(HelloServiceTest.java:30)
[error]     ...
[error] Caused by: io.grpc.StatusRuntimeException: UNKNOWN
[error]     at io.grpc.Status.asRuntimeException(Status.java:532)
[error]     at akka.grpc.internal.UnaryCallAdapter.onClose(UnaryCallAdapter.scala:43)
[error]     at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
[error]     at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
[error]     at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
[error]     at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
[error]     at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
[error]     at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
[error]     at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
[error]     at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:398)
[error]     at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
[error]     at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
[error]     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
[error]     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
[error]     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
[error]     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[error]     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
[error]     ... 3 more
[error] Caused by: java.lang.Exception: Failed ALPN negotiation: Unable to find compatible protocol.
[error]     at io.grpc.netty.shaded.io.grpc.netty.ProtocolNegotiators$ClientTlsHandler.userEventTriggered(ProtocolNegotiators.java:336)
[error]     at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:326)
[error]     at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:312)
[error]     at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:304)
[error]     at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1745)
[error]     at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1410)
[error]     at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1225)
[error]     at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1272)
[error]     at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
[error]     at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
[error]     at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
[error]     at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[error]     at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[error]     at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
[error]     at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
[error]     at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[error]     at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[error]     at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
[error]     at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[error]     at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
[error]     at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
[error]     at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
[error]     at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
[error]     at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
[error]     at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[error]     ... 1 more
[info] Test run finished: 1 failed, 0 ignored, 2 total, 14.026s
[error] Failed: Total 2, Failed 1, Errors 0, Passed 1
[error] Failed tests:
[error] 	com.example.hello.impl.HelloServiceTest
```

**Comment by TimMoore** [comment]
@dwijnand I saw that. Any idea why this change would cause that?

**Comment by dwijnand** [comment]
No, but I'd be fine with leaving the gRPC things on older sbt until we rotate back to gRPC things.

**Comment by TimMoore** [comment]
Pretty surprising that it only affects the Java project and not the Scala one, though. I'll do a bit of time-boxed investigation and otherwise roll that one project back.

**Comment by TimMoore** [comment]
The reason for the difference is that `grpc-example-scala` wasn't ever updated to Lagom 1.6.0-Mx. If I downgrade `grpc-example-java` to Lagom 1.5.3, or upgrade `grpc-example-scala` to 1.6.0-M5, then I see consistent behavior between them.

So, it's a multi-part incompatibility between Lagom 1.6 (or something it brings in), gRPC, and sbt 1.3.x. Looking at the classpaths, I can see that sbt 1.3.x is resolving differently than 1.2.8. In particular, it's using gRPC 1.20.0 in 1.3.x vs 1.16.1 in 1.2.8.

**Comment by TimMoore** [comment]
That in turn is because it's selecting `akka-grpc-runtime` 0.6.1, but I can't tell why that is, because it appears to depend directly on 0.6.0 and there is no eviction message.

**Comment by TimMoore** [comment]
This is too complicated for me to understand. It seems likely that there is an sbt bug here, but I don't know how to simplify it. The dependency on `akka-grpc-runtime` is added to the project dynamically by the Akka gRPC sbt plugin, and it looks like the right version is added, but a different version is actually resolved.

CC: @eed3si9n

Anyway, moving on: this is superseded by #104.

**Comment by TimMoore** [comment]
This seems similar to https://github.com/coursier/coursier/issues/1053, and perhaps related to https://github.com/coursier/coursier/issues/1382. I verified that disabling Coursier in sbt 1.3.2 does work correctly.

**Comment by TimMoore** [comment]
Mystery solved: it's because this project depends on `lagom-javadsl-grpc-testkit` 0.7.0 in the `Test` scope, which then depends on `akka-grpc-runtime` 0.6.1. Because of https://github.com/coursier/coursier/issues/1382, Coursier handles this differently than sbt+Ivy.

So why does it work with Lagom 1.5.3? That also resolves to `akka-grpc-runtime` 0.6.1 on sbt 1.3.2+Coursier. Some other other dependencies are different, though, such as the Netty version, so I guess it must be a conflict between particular versions.

**Pull request closed without merging**
