### PR TITLE
Update to Lagom 1.6.0-RC2

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Review by ignasi35 — APPROVED** [review]

**Comment by ignasi35** [comment]
This is very confusing:

```
2019-11-08 11:18:42,521 INFO  com.datastax.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer

2019-11-08 11:18:42,546 ERROR akka.actor.OneForOneStrategy - play/reference-overrides.conf @ jar:file:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lightbend/lagom/lagom-persistence-cassandra-core_2.12/1.6.0-RC2/lagom-persistence-cassandra-core_2.12-1.6.0-RC2.jar!/play/reference-overrides.conf: 66: Configuration key 'keyspace' is set to null but expected STRING

akka.actor.ActorInitializationException: akka://application/system/cassandra-snapshot-store: exception during creation

	at akka.actor.ActorInitializationException$.apply(Actor.scala:195)

	at akka.actor.ActorCell.create(ActorCell.scala:657)

	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)

	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)

	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)

	at akka.dispatch.Mailbox.run(Mailbox.scala:229)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.reflect.InvocationTargetException: null

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

	at akka.util.Reflect$.instantiate(Reflect.scala:69)

	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:100)

	at akka.actor.Props.newActor(Props.scala:226)

	at akka.actor.ActorCell.newActor(ActorCell.scala:609)

	at akka.actor.ActorCell.create(ActorCell.scala:635)

	... 7 common frames omitted
```

Build fails because `lagom-persistence-cassandra-core` fails to load a setting. But I don't see where/how is `lagom-persistence-cassandra-core` mixed in.

**Comment by ignasi35** [comment]
OK, so
```
sbt:couchbase-persistence-scala-sbt> test:whatDependsOn com.lightbend.lagom lagom-persistence-cassandra-core_2.12 1.6.0-RC2
[info] com.lightbend.lagom:lagom-persistence-cassandra-core_2.12:1.6.0-RC2 [S]
[info]   +-com.lightbend.lagom:lagom-scaladsl-persistence-cassandra_2.12:1.6.0-RC2 [S]
[info]     +-com.lightbend.lagom:lagom-scaladsl-testkit_2.12:1.6.0-RC2 [S]
[info]       +-com.lightbend.lagom.sample.couchbase:hello-impl_2.12:1.0-SNAPSHOT [S]
[info]
[success] Total time: 2 s, completed Nov 8, 2019 12:59:45 PM
```

but why is `lagom-persistence-cassandra-core` starting the `CassandraJournal` eagerly?

**Comment by ignasi35** [comment]
This is even weirder. 

In order to use `sbt-dependency-graph` I rolled back to sbt `1.2.8`. The test now passes.

I've run the test in some combinations (`lagomForkedTestSettings` or not, `1.2.8` vs `1.3.2`, etc...) and I can only reproduce the error using sbt `1.3.2`. 

What I found even more confusing is that I could understand issues cause by sbt `1.3` having changed the Classloading internally, but the tests also fail when running forked.

**Comment by ignasi35** [comment]
> Let's try 1.3.3 then

I don't think so. Just tried it locally.

**Comment by marcospereira** [comment]
https://github.com/lagom/lagom/issues/2450 created so that we don't lose track of this problem.

**Pull request merged**
