### PR TITLE
Lagom 1.5.0

### PR DESCRIPTION
**Pull request by octonato**

### CODE REVIEW

**Comment by ignasi35** [comment]
LGTM. Have you tried running the couchbase and telemetry samples locally? (they don't run on travis)

**Comment by octonato** [comment]
> Have you tried running the couchbase and telemetry samples locally? (they don't run on travis) 

I'm working to make couchbase runnable on travis. Telemetry won't work, but I will run locally. On my TODO list.

**Comment by octonato** [comment]
@ignasi35, I downgraded Cinnamon to 2.10.17. I'm getting issues in downloading 2.11.1. 

The Couchbase tests are being covered here: #2

**Comment by octonato** [comment]
Update:

Issue with Cinnamon 2.11.1 is solved. `chmetrics` is not cross compiled anymore. 

However, app doesn't start because of play secret. I added it but it's not picking. I will continue tomorrow with a fresh head.

**Review by marcospereira — DISMISSED** [review]

**Comment by ignasi35** [comment]
> However, app doesn't start because of play secret. I added it but it's not picking. I will continue tomorrow with a fresh head.

Are you setting the secret in the [`pom.xml`](https://github.com/lagom/lagom-samples/blob/cc68dc8b1ad2901aee9bdc021d16170084d68f80/lightbend-telemetry/lightbend-telemetry-java-mvn/pom.xml#L58)? These samples use a forked run to attach the telemetry agent and set a (very) weak secret (which was OK on Play 2.6.x).

**Comment by octonato** [comment]
No, I was adding it to `application.conf` and of course, the pom was overriding it.

**Comment by octonato** [comment]
It's fixed. I added the a stronger secret on the pom.

I would have preferred to have it in the `application.conf` with a mention to not copy-and-paste it. This is a sample app, not a production app. It would have made things less obscure. I lost quite some time chasing that. Thanks for the tip, @ignasi35.

I tested both telemetry apps and it works with Lagom 1.5.0 and Cinnamon 2.11.1 as expected. 

This can be merged, IMO.

**Comment by ignasi35** [comment]
> I would have preferred to have it in the `application.conf` with a mention to not copy-and-paste it. This is a sample app, not a production app. It would have made things less obscure. I lost quite some time chasing that. Thanks for the tip, @ignasi35.

Can't you remove the setting from the pom (and let Play pick it from `application.conf`)?

**Comment by octonato** [comment]
Done! 9b87eb5

**Pull request merged**
