### PR TITLE
Make mvn package work without .git directory

### LINKED ISSUE #76: Shopping Cart Maven build breaks when used with Tech Hub project starter
# Reproduction

1. Go to https://developer.lightbend.com/start/?group=lagom&project=lagom-samples-lagom-java-shopping-cart-example
2. Click "Create a project for me"
3. Unzip the downloaded `lagom-samples-lagom-java-shopping-cart-example.zip`
4. `cd lagom-samples-lagom-java-shopping-cart-example/`
5. `mvn package`

```text
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.413 s
[INFO] Finished at: 2019-07-09T08:27:34+09:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.6:revision (default) on project shopping-cart-api: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :shopping-cart-api
```

The problem is that the included `maven-git-commit-id-plugin` expects to be run in side a git repository, but when provided from the project starter, the resulting directory isn't a git repo.

### PR DESCRIPTION
**Pull request by octonato**
Fixes #76

### CODE REVIEW

**Comment by ignasi35** [comment]
Hmm, removing this may break deployment, doesn't it? Or will need reviewing the deployment documentation. 

I don't think `shopping-cart` makes a lot of sense as a tech-hub starter project.

**Comment by TimMoore** [comment]
That's a good point, @ignasi35. Maybe better to remove it from the list on Tech Hub.

**Comment by octonato** [comment]
@ignasi35, what do you mean by "removing this may break deployment"? Removing what?

**Comment by ignasi35** [comment]
> @ignasi35, what do you mean by "removing this may break deployment"? Removing what?

I assumed the change removed some plugin/hack used to produce the version from the `.git` history. I just realized the actual change is not better: in order to make `shopping-cart` usable from tech-hub we're adding even more code on the `pom.xml`.

I think `shopping-cart` is not a sample that should be available from `tech-hub` and we should try to keep it as simple as possible to go with the deployment guides. If we deem absolutely necessary that `shopping-cart` is downloadable from tech-hub, then, instead of adding more code, I'd simplify it (even hardcode the version) via removing any git-specific, `ant-run` or any other hack.

**Comment by octonato** [comment]
Ok, I will close it and remove from TechHub

**Comment by octonato** [comment]
Well, I just realised that we have decided that shopping-cart IS our main demo app in which we demo the main features in Lagom. That said, I think we should have it on TechHub. 

I'm re-opening this PR for now. We can decide to remove the git id from the build. Both are fine for me.

**Comment by octonato** [comment]
Ok, we decided in meeting to remove it from TechHub

**Pull request closed without merging**
